## 1. Tensor Math

In [1]:
import torch

**Tensor Initiation From Uniform Distribution:**

First, let’s instantiate two random tensors, one with uniform distribution in the range [–1, 1) and the
other with a standard normal distribution:

In [2]:
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))

print("Random standard normal distribution:\n",t1)
print("\nFrom distribution where, mean=0 std=1:\n",t1)

print("\n\nMean (t1) => ", torch.mean(t1))
print("Mean (t2) => ", torch.mean(t2))

print("\n\nStandard Dev (t1) => ", torch.std(t1))
print("Standard Dev (t2) => ", torch.std(t2))

Random standard normal distribution:
 tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])

From distribution where, mean=0 std=1:
 tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])


Mean (t1) =>  tensor(0.0327)
Mean (t2) =>  tensor(-0.0620)


Standard Dev (t1) =>  tensor(0.5043)
Standard Dev (t2) =>  tensor(0.8870)


Now we can calculate:
- torch.mean(<torch_tensor>, axios=..)
- torch.sum(<torch_tensor>, axios=..)

**Examples**
- Mean along different axis

In [3]:
t1 = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

t2 = torch.mean(t1, axis=0, dtype=float)

**Addition:**

In [4]:
x = torch.tensor([1, 2, 3])

y = torch.tensor([4, 5, 6])

z = x + y

print(z)
print(torch.add(x, y))

tensor([5, 7, 9])
tensor([5, 7, 9])


**Subtraction**

In [5]:
x = torch.tensor([4, 5, 6])
y = torch.tensor([1, 2, 3])

z = x - y

print(z)

print(torch.sub(x, y))

tensor([3, 3, 3])
tensor([3, 3, 3])


**Division:**
- Resulting Tensor in float

In [6]:
x = torch.tensor([4, 6, 10])

y = torch.tensor([2, 3, 5])


# y can be a tensor
print("Div two tensor: ", torch.true_divide(x, y))

# y can be scalar value too
print("Divice tensor by scalar: ",torch.true_divide(x, 2))

Div two tensor:  tensor([2., 2., 2.])
Divice tensor by scalar:  tensor([2., 3., 5.])


**Exponential:**

In [7]:
x = torch.tensor([2, 4, 6])

print("x pow 2:", x ** 2)

print("x pow 2", x.pow(2))

x pow 2: tensor([ 4, 16, 36])
x pow 2 tensor([ 4, 16, 36])


# 2. Matrix and Vector

**Matrix Multiplication:**
- Note that, `x*y` is a point wise matrix multiplication

In [8]:
x = torch.rand((2, 5)) # 2 by 5
y = torch.rand((5, 3)) # 5 by 3

z = x.mm(y) ## 2 by 3

z

tensor([[1.3600, 0.9623, 1.6286],
        [1.3535, 0.6815, 1.5394]])

**Point Wise Matrix Multiplication:**
- Multiplies each corresponding element

In [9]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [6, 7, 9]])

y = torch.tensor([[3, 2, 1],
                  [8, 5, 7],
                  [4, 1, 2]])

x * y

tensor([[ 3,  4,  3],
        [32, 25, 42],
        [24,  7, 18]])

**Matrix Exponentiation:**
- $A^3=A*A*A$

In [10]:
a = torch.rand((5, 5))
a.matrix_power(3)

tensor([[5.1329, 4.9755, 5.1755, 4.3024, 4.3187],
        [4.4042, 4.4884, 4.7840, 3.8775, 3.5630],
        [2.5137, 2.5602, 2.7277, 2.3210, 2.0627],
        [4.7394, 4.7458, 4.8686, 4.1209, 3.9426],
        [4.0713, 4.2954, 4.4823, 3.7487, 3.3707]])

**Vector Dot Product:**

In [11]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

z = x.dot(y)

z

tensor(32)

## 3. Batch Matrix Multiplication:
- Matrix multiplication in batch

In [12]:
batch = 2
n = 2
m = 3
p = 4


t1 = torch.rand(batch, n,m) # two batch of  2x3 matrix
t2 = torch.rand(batch, m,p) # two batch  3x4 matrix

t3 = t1.bmm(t2) # two batch of  2x4 matrix

print("t1: ", t1)
print("\nt2: ", t2)
print("\nt3: ", t3)

print("\nSize => ",t3.shape)

t1:  tensor([[[0.1484, 0.1227, 0.5304],
         [0.4148, 0.7937, 0.2104]],

        [[0.0555, 0.8639, 0.4259],
         [0.7812, 0.6607, 0.1251]]])

t2:  tensor([[[0.6004, 0.6201, 0.1652, 0.2628],
         [0.6705, 0.5896, 0.2873, 0.3486],
         [0.9579, 0.4075, 0.7819, 0.7165]],

        [[0.1768, 0.0748, 0.9799, 0.5261],
         [0.8427, 0.6036, 0.6608, 0.8735],
         [0.9741, 0.1682, 0.5625, 0.8731]]])

t3:  tensor([[[0.6795, 0.3805, 0.4745, 0.4618],
         [0.9828, 0.8109, 0.4611, 0.5365]],

        [[1.1527, 0.5972, 0.8648, 1.1556],
         [0.8168, 0.4783, 1.2725, 1.0974]]])

Size =>  torch.Size([2, 2, 4])


# 4. Broadcasting:

**Given tensors:**

$$
\mathbf{X} = \begin{bmatrix}
10 & 20 & 30 \\
40 & 50 & 60 \\
60 & 70 & 80
\end{bmatrix}
\quad
\mathbf{Y} = \begin{bmatrix}
10 & 20 & 30
\end{bmatrix}
$$

**Broadcasting Mechanism:**

$$
\mathbf{Y}_{\text{broadcasted}} = \begin{bmatrix}
10 & 20 & 30 \\
10 & 20 & 30 \\
10 & 20 & 30
\end{bmatrix}
$$

**Element-wise Subtraction:**

$$
\mathbf{X} - \mathbf{Y}_{\text{broadcasted}} =
\begin{bmatrix}
10 - 10 & 20 - 20 & 30 - 30 \\
40 - 10 & 50 - 20 & 60 - 30 \\
60 - 10 & 70 - 20 & 80 - 30
\end{bmatrix}
=
\begin{bmatrix}
0 & 0 & 0 \\
30 & 30 & 30 \\
50 & 50 & 50
\end{bmatrix}
$$


In [13]:
x = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [60, 70, 80]])

y = torch.tensor([[10, 20, 30]])

x - y

tensor([[ 0,  0,  0],
        [30, 30, 30],
        [50, 50, 50]])

In [14]:
x + y

tensor([[ 20,  40,  60],
        [ 50,  70,  90],
        [ 70,  90, 110]])

In [15]:
x * y

tensor([[ 100,  400,  900],
        [ 400, 1000, 1800],
        [ 600, 1400, 2400]])

## 5. Other Useful Operations

**Sum accross dimensions:**

Given a nxm matrix

In [16]:
x = torch.rand(4, 5)
x

tensor([[0.8622, 0.8106, 0.1381, 0.1399, 0.1976],
        [0.5628, 0.9983, 0.1842, 0.7664, 0.2233],
        [0.0299, 0.3937, 0.7881, 0.9642, 0.1895],
        [0.6085, 0.9314, 0.8313, 0.8116, 0.8553]])

In [17]:
torch.sum(x, dim=1)

tensor([2.1485, 2.7350, 2.3654, 4.0382])