# Basic Tensor Operations In Pytorch

In [1]:
# !pip install torch
import torch


## 1. Initializing a Tensor

In [2]:

torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

**With Datatypes: dtype=**

In [3]:
torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**On device: device=**
- cuda / cpu

In [4]:
torch.tensor(
    [[1, 2, 3], [4, 5, 6]],
    dtype=torch.int32, device="cuda")

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0', dtype=torch.int32)

**require_grad**
- Boolean
- Used when computing auto grad, automatic gradients

Note that, only a tensor with datatype float allows grad.

In [5]:
t = torch.tensor(
    [[1, 2, 3], [4, 5, 6]], 
    dtype=torch.float16,
    device="cuda",
    requires_grad=True
)

print("Tensor: ", t)

print("Data Type: ", t.dtype)
print("Device: ", t.device)
print("Shape: ", t.shape)
print("Requires Grad: ", t.requires_grad)

Tensor:  tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float16,
       requires_grad=True)
Data Type:  torch.float16
Device:  cuda:0
Shape:  torch.Size([2, 3])
Requires Grad:  True


**Empty and Zeros Initialization:**

In [6]:
emp = torch.empty(
    size=(3,3)
)

zr = torch.zeros(
    size=(3, 3)
)

print("Empty: ",emp)
print("Zeros: ",zr)

Empty:  tensor([[1.5766e-19, 1.0256e-08, 4.2004e-05],
        [3.1643e+12, 6.7743e-10, 1.6902e-04],
        [1.0781e-08, 1.2401e+16, 2.1707e-18]])
Zeros:  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


**From Uniform Distribution:**
- In interval of 0 and 1

In [7]:
x = torch.rand(
    size=(3,3)
)
x

tensor([[0.5794, 0.9810, 0.7186],
        [0.9805, 0.7314, 0.5563],
        [0.7161, 0.4887, 0.3430]])

**Ones and Eye**

In [8]:
# All elements one
ones = torch.ones(
    size=(3, 3)
)

# Identity Matrix
# Diagonal Element => 1, Non Diag => 0
i = torch.eye(
    n=3
)

print("Ones: ", ones)
print("Ey: ", i)

Ones:  tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Ey:  tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


**Range**

In [9]:
x = torch.arange(
    start=0,
    end=5,
    step=1
)

x

tensor([0, 1, 2, 3, 4])

**Initialization In Normal Distrivution:**
- Given mean and standard deviation

In [10]:
x_norm = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x_norm

tensor([[ 2.7027, -0.2846,  0.4500,  1.0411, -0.8529]])

**Diagonal Matrix:**

In [11]:
dg = torch.diag(torch.ones(2))
dg

tensor([[1., 0.],
        [0., 1.]])

## 2. Conversion To Different Types: (int, float, double):
- Default Int type is: **int64**
- Default Float Type is: **float32**

In [12]:
t = torch.arange(10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print("To Boolean", t.bool())
print("To int16:",t.short())
print("To int64:",t.long())
print("To float16:",t.half())
print("To float32:",t.float())
print("To float64:",t.double())

To Boolean tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])
To int16: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)
To int64: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
To float16: tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)
To float32: tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
To float64: tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


## 3. Array To Tensor And Vice Versa

In [14]:
import numpy as np

In [15]:
np_array = np.zeros((5, 5))
np_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**Np array to Tensor: torch.numpy(\<numpy_arr>)**

In [16]:
tensor = torch.from_numpy(np_array)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

**Tensor To Numpy: \<tensor>\.numpy()**

In [17]:
# back to numpy array
np_array_back = tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])