In [1]:
import torch

## 1. Random Number from Normal Distribution

In [2]:
# Create a random tensor of shape (3, 4)

x = torch.randn(3, 4)
print(x)

tensor([[-0.2177, -0.2284,  0.4515,  0.2953],
        [-2.0208,  0.9088, -0.4401,  1.2220],
        [-1.3709, -0.1324,  0.6600, -0.6063]])


## 2. View

What it does: Reshapes a tensor without changing its data. It's the most common way to flatten or expand dimensions. Rule: The total number of elements must remain the same ($B×T×C$ must equal the new dimensions multiplied).


In [3]:
# generate random tensor of shape (1,2,3) in normal distribution
x = torch.randn(1, 2, 3)

# Reshape tensor
y = x.view(2, 3)

print("X = ", x)
print("\n\nX shape = ",x.shape)

print("\n\nY = ", y)
print("\nY shape = ",x.shape)

X =  tensor([[[-0.7207, -0.2683, -2.6971],
         [ 0.8406, -1.0783, -0.0155]]])


X shape =  torch.Size([1, 2, 3])


Y =  tensor([[-0.7207, -0.2683, -2.6971],
        [ 0.8406, -1.0783, -0.0155]])

Y shape =  torch.Size([1, 2, 3])


## 3. Splitting a Tensor

In [4]:
# generate random tensor of shape (2,4)
x = torch.randn(2, 4)
print("\nx = ",x)
print("\nx shape = ",x.shape)

# Split tensor into 2 parts along dimension 1 i.e. columns
y = x.split(2, dim=1)
print("\ny = ",y)
print("\ny shape = ",[i.shape for i in y])


x =  tensor([[ 0.8058,  2.2228, -0.7108, -2.0611],
        [ 0.1706, -0.2283, -0.2711,  0.9762]])

x shape =  torch.Size([2, 4])

y =  (tensor([[ 0.8058,  2.2228],
        [ 0.1706, -0.2283]]), tensor([[-0.7108, -2.0611],
        [-0.2711,  0.9762]]))

y shape =  [torch.Size([2, 2]), torch.Size([2, 2])]


## 4. Unsqueezing a tensor

In [6]:
pos = torch.arange(0, 10) # Shape: (10)
print("pos: ",pos)
print(f"Pos: {pos.shape}")


pos_batch = pos.unsqueeze(0) # Shape: (1, 10)
print("\n\npos_batch: ",pos_batch)
print(f"Pos Batch: {pos_batch.shape}")

pos:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Pos: torch.Size([10])


pos_batch:  tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
Pos Batch: torch.Size([1, 10])


## 5. Masked Filling

In [19]:
x = torch.randn(3)

masked = torch.tensor([True, False, True])

print(x)
print(masked)

print(x.masked_fill(masked, -999))


tensor([-1.2008,  1.9858, -0.4268])
tensor([ True, False,  True])
tensor([-999.0000,    1.9858, -999.0000])
